### ISSUE TITLE
Issue with install

### ISSUE THREAD

**Issue by TYO79** [Durman/BuildingNodesDocs#14]
Hi Durman

i Bought Building Node yesterday and tried to install it, but i Have this error message while activating the addon (see attached File).

I tried to Load Factory Setting and then it works. How can i  do to solve this issue?

Thanks for your answer

Best Regard

ERROR:

Exception in module register(): C:\Users\Windows\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\building_nodes\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 387, in enable
    mod.register()
  File "C:\Users\Windows\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\building_nodes\__init__.py", line 3097, in register
    nodeitems_utils.register_node_categories('CUSTOM_NODES', get_node_categories())
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\nodeitems_utils.py", line 105, in register_node_categories
    raise KeyError("Node categories list '%s' already registered" % identifier)
KeyError: "Node categories list 'CUSTOM_NODES' already registered"

![INSTALL_BUILDING_NODE](https://user-images.githubusercontent.com/54005247/159114211-43119882-0c3c-4fb3-a089-b5a4e5325940.jpg)

**Comment by Durman** [comment]
Hello. It seems there is name overlapping with another add-on. I would ask perform next steps.

1. Disable all custom add-ons.
2. Restart Blender
3. Enable BuildingNodes add-on. (There should not be any problems)
4. Try to enable all other custom add-ons. If some of them fails it means I'm right.

**Comment by TYO79** [comment]
Hi,
Thanks for your answer.
 Well i’ve more than 30 addons installed it will be boring but i gess i dint have any other choice:)


> ////////////////////////////////// Yann Terrer
> //////////////// ***@***.***
> //////////////// tel: + 33 6 63 10 92 62
> ///////////////////// www.yannterrer.com
>

**Comment by TYO79** [comment]
In fact i enter in your Code and replace in line 3097 and 3136: "CUSTOM_NODES" by "CUSTOM_NODES_B" (Like CUSTOM_NODE_BUILDING" and it worked!!!
As Geonod will become a growing pert in Blender, CUSTOM_NODE is too commun in my opinion:)

Bests

**Comment by Durman** [comment]
If I would know that you can edit code I suggested to do this at the start.))
I will fix it too in a future version.

**Comment by TYO79** [comment]
No problem, I'm just crying with what i'm seeing right now;)
Is there any means to add as Sequence Sode like the Random one to fill facade with a specific order of pannel?

**Comment by Durman** [comment]
Probably you are looking this node https://durman.github.io/BuildingNodesDocs/nodes/panel/join_panels.html

**Comment by TYO79** [comment]
Absolutely, sorry for bother you, everything is in your Doc;)
